server:
  port: 8008
spring:
  application:
    name: ${service.name:cocache-example}
  redis:
    url: redis://localhost:6379

cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: redis
    state-storage:
      local:
        state-location: ./cosid-machine-state/
  snowflake:
    enabled: true
    share:
      clock-sync: true
      friendly: true
      converter:
        type: radix

cocache:
  enabled: true

logging:
  level:
    me.ahoo: debug
