server:
  port: 8008
spring:
  application:
    name: ${service.name:cocache-example}
  data:
    redis:
      host: localhost
cocache:
  enabled: true

logging:
  level:
    me.ahoo: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - cocache
          - cocacheClient
springdoc:
  show-actuator: true