server:
  port: 8008
spring:
  application:
    name: ${service.name:cocache-example}
  redis:
    url: redis://localhost:6379

cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: redis
  generator:
    enabled: true

cocache:
  enabled: true

logging:
  level:
    me.ahoo: debug
management:
  endpoints:
    web:
      exposure:
        include:
          - cocache
          - cocache-client
