server:
  port: 8008
spring:
  application:
    name: ${service.name:cocache-example}
  redis:
    url: redis://localhost:6379

cosid:
  namespace: ${spring.application.name}
  snowflake:
    enabled: true
    machine:
      distributor:
        type: redis
      state-storage:
        local:
          state-location: ./cosid-machine-state/
    share:
      clock-sync: true
      friendly: true
      converter:
        type: radix

logging:
  level:
    me.ahoo: debug
