@startuml

!include layout.puml

title
CoCache
__Sequence Diagram__
end title

actor User
participant CoherentCache
participant ClientSideCache
participant DistributedCache
participant CacheSource
queue CacheEvictedEventBus

User++
CoherentCache ++
CoherentCache -> CacheEvictedEventBus++ : subscribe
User -> CoherentCache : get(key)
CoherentCache -> ClientSideCache++ : get(key)
alt cache exist
    CoherentCache <-- ClientSideCache-- : cache
else cache not exist
    CoherentCache -> DistributedCache++ : get(key)
    CoherentCache <-- DistributedCache-- : cache
    alt cache exist
        CoherentCache -> ClientSideCache++ : setCache(key, value)
        ClientSideCache--
    else cache not exist
        CoherentCache -> CacheSource++ : load(key)
        CoherentCache <-- CacheSource-- : source
        alt source is not null
            CoherentCache -> ClientSideCache++ : setCache(key, source)
            ClientSideCache--
            CoherentCache -> DistributedCache++ : setCache(key, source)
            DistributedCache--
        else source is null
            CoherentCache -> ClientSideCache++ : setCache(key, missingGuard())
            ClientSideCache--
            CoherentCache -> DistributedCache++ : setCache(key, missingGuard())
            DistributedCache--
        end
    end
end

User <-- CoherentCache : cache
@enduml
