name: Sync to Gitee
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: gitee-sync
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:Ahoo-Wang/CoCache.git"
          destination-repo: "git@gitee.com:AhooWang/CoCache.git"
